"use client";
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  Navbar,
  NavBody,
  NavItems,
  NavbarLogo,
  NavbarButton,
  MobileNav,
  MobileNavHeader,
  MobileNavToggle,
  MobileNavMenu,
} from "../components/ui/resizable-navbar";
import { Inter } from "next/font/google";
import Footer from "../components/Footer";
import Link from "next/link";
import { useState } from "react";
import { Toaster } from "react-hot-toast";

// Initialize the font object
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const navItems = [
  { name: "Home", link: "/" },
  { name: "About", link: "/about" },
  { name: "Work", link: "/works" },
  { name: "Contact", link: "/contact" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [visible] = useState(false);
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} antialiased border-0 border-green-600 flex flex-col min-h-screen`}
      >
        <div className="border-0 border-green-400 pt-[0px]">
          <Navbar>
            <NavBody>
              <NavbarLogo />
              <NavItems items={navItems} />
              <NavbarButton href="/login" variant="primary">
                Get Started
              </NavbarButton>
            </NavBody>

            <MobileNav visible={visible}>
              <MobileNavHeader>
                <NavbarLogo />
                <MobileNavToggle
                  isOpen={isMobileMenuOpen}
                  onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
                />
              </MobileNavHeader>

              <MobileNavMenu
                isOpen={isMobileMenuOpen}
                onClose={() => setIsMobileMenuOpen(false)}
              >
                {/* Mobile menu items */}
                <div className="flex flex-col w-full gap-4">
                  <Link href="/" className="text-black dark:text-white">
                    Home
                  </Link>
                  <Link href="/about" className="text-black dark:text-white">
                    About
                  </Link>
                  <Link href="/services" className="text-black dark:text-white">
                    Services
                  </Link>
                  <Link href="/contact" className="text-black dark:text-white">
                    Contact
                  </Link>
                  <NavbarButton variant="primary" className="mt-4">
                    Get Started
                  </NavbarButton>
                </div>
              </MobileNavMenu>
            </MobileNav>
          </Navbar>
        </div>

        <div className="flex-grow h-fit">
          <Toaster position="top-right" />
          {children}
        </div>

        <Footer />
      </body>
    </html>
  );
}
