"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "../components/Footer";
import Link from "next/link";
import { useState } from "react";
import {ToastContainer} from "react-toastify"
import StoreProvider from "./StoreProvider";
import NavBar from "../components/NavBar";
import { usePathname } from "next/navigation";
import Sidebar from "../components/SidebarWrapper";
import { useSelector } from "react-redux";
import { motion } from "framer-motion";
import App from "next/app";
import AppLayout from "./AppLayout";

// Initialize the font object
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const navItems = [
  { name: "Home", link: "/" },
  { name: "About", link: "/about" },
  { name: "Work", link: "/works" },
  { name: "Contact", link: "/contact" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [visible] = useState(false);
  const pathname = usePathname();
  const hideNavbar = pathname.startsWith("/conference/");
  // const { isOpen } = useSelector((state: any) => state.sideBar);
  return (
    <html lang="en" className="dark">
      <StoreProvider>
      <body
        className={`${inter.className} antialiased border-0 border-green-600 flex flex-col min-h-screen`}
      >
        {/* <div className="border-1 border-green-500">
          { !hideNavbar && <NavBar></NavBar>}
        </div>

        <motion.div
            className="flex-grow transition-transform relative z-0"
            animate={{
              x: isOpen ? "-24rem" : "0rem", // shift left by sidebar width
            }}
            transition={{
              type: "spring",
              stiffness: 300,
              damping: 30,
            }}
          >
            <ToastContainer position="bottom-center" />
            {children}
            <Footer />
          </motion.div>
          <Sidebar></Sidebar> */}
          <AppLayout>{children}</AppLayout>
      </body>
      </StoreProvider>
    </html>
  );
}
